###   When Autolock is disabled, wait 30 minutes
###   and then run enable Autolock script

alias: Autolock Disabled
trigger:
  platform: state
  entity_id: input_boolean.autolock
  state: 'off'
action:
  - service: script.enable_autolock
  - service: script.turn_off
    entity_id: script.autolock
  - service: lock.unlock
    entity_id: lock.front_door_lock_88