###   When Lock is unlocked run the Autolock script

alias: Autolock Enabled
trigger:
  platform: state
  entity_id: lock.front_door_lock_88
  state: 'unlocked'
condition:
- condition: state
  entity_id: input_boolean.autolock
  state: 'on'
action:
  - service: script.autolock