###   Turn Living Fans Off when temperature is Low

alias: Living Fans off Temp Low
trigger:
  platform: numeric_state
  entity_id: sensor.living_room_temp
  below: 73
action:
  - service: switch.turn_off
    entity_id: switch.living_room_fan_33