###   Set a timer when the fan is turned off

alias: Manual Fan Select
trigger:
- platform: state
  entity_id: switch.living_room_fan_33
action:
  - service: script.turn_off
    data:
      entity_id: script.timer_living_fan
  - service: automation.turn_off
    entity_id: automation.living_fans_on_temp_high
  - service: script.turn_on
    data:
      entity_id: script.timer_living_fan
    