###   Turn Living Fans on when temperature is high

alias: Bedroom Fans On Temp High
trigger:
- platform: numeric_state
  entity_id: sensor.temp__bedroom_100
  above: 70
- platform: time
    # Matches every hour at 5 minutes past whole
  minutes: 20
  seconds: 00
condition:
- condition: numeric_state
  entity_id: sensor.temp__bedroom_100
  above: 70
action:
  - service: switch.turn_on
    entity_id: switch.bedroom_fan_11