###   Cancel Bathroom Timer when humidity is high

alias: Bathroom Humidity High
trigger:
  platform: numeric_state
  entity_id: sensor.humidity__bathroom_79
  above: 49
action:
  - service: script.turn_off
    data:
      entity_id: script.timer_bathroom_set
  - service: switch.turn_on
    entity_id: switch.bathroom_fan_9