####  Unlock Door when someone arrives

alias:  Unlock Door on Arrival
trigger:
- platform: state
  entity_id: group.charlotte_occupancy
  to: 'home'
- platform: state
  entity_id: group.chris_occupancy
  to: 'home'
action:
- service: lock.unlock
  entity_id: lock.front_door_lock_88