###   When closet light is turned on soon after the short script
###   is run, set a script to extend time

alias: Closet Light Extend Timer
trigger:
  platform: state
  entity_id: light.closet_light_3
  from: 'off'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: script.timer_closet_short_set
      state: 'on'
    - condition: state
      entity_id: script.timer_closet_long_set
      state: 'on'  
action:
- service: script.turn_off
  entity_id: script.timer_closet_short_set
- service: script.turn_off
  entity_id: script.timer_closet_long_set
- service: script.turn_on
  entity_id: script.timer_closet_long_set  