###   Turns Sleep Mode Off when motion is detected downstairs in the morning
###   Also sets all of the house modes to sleeping

alias: Sleep Mode Off
trigger:
- platform: state
  entity_id: binary_sensor.motion__kitchen_27
  to: 'on'
condition:
- condition: state
  entity_id: input_boolean.sleep_mode
  state: 'on'
- condition: and
  conditions:
  - condition: time
    after: '06:01:00'
  - condition: time
    before: '20:59:00'
action:
- service: input_boolean.turn_off
  entity_id: input_boolean.sleep_mode
- service: joaoapps_join.phoebe_join_send_tasker
  data:
    command: "setvar=:=SLEEPING=:=no"