###   When motion is detected in the Bathroom,
###   run the script Motion BAthroom Light which
###   turns on the Bathroom Lights and cancels
###   previously set timers

alias: Motion in Bathroom
trigger:
  platform: state
  entity_id: binary_sensor.motion__bathroom_76
  state: 'on'
action:
  - service: script.turn_off
    data:
      entity_id: script.timer_bathroom_set
  - condition: or
    conditions:
      - condition: state
        entity_id: light.bathroom_light_4
        state: 'off'
      - condition: state
        entity_id: light.bathroom_light_4
        state: 'off'
  - service: script.motion_bathroom_light