###   When motion is detected in the Kitchen,
###   run the script Motion Kitchen Light which
###   turns on the Kitchen Lights and cancels
###   previously set timers

alias: Motion in Kitchen
trigger:
  platform: state
  entity_id: binary_sensor.motion__kitchen_27
  state: 'on'
action:
  - service: script.turn_off
    data:
      entity_id: script.timer_kitchen_set
  - condition: or
    conditions:
      - condition: state
        entity_id: light.main_parent__cabinet_lights_67
        state: 'off'
      - condition: state
        entity_id: light.kitchen_light_28
        state: 'off'
  - service: script.motion_kitchen_light