###   When no motion is detected, run the script
###   No Motion Kitchen Timer.  When the timer expires
###   the Kitchen Lights turn Off

alias: No Motion in Kitchen
trigger:
  platform: state
  entity_id: binary_sensor.motion__kitchen_27
  from: 'on'
action:
- service: script.timer_kitchen_set