###   When no motion is detected, run the script
###   Timer Bedroom Set.  When the timer expires
###   the Bedroom Lights turn Off

alias: No Motion in Bedroom
trigger:
  platform: state
  entity_id: binary_sensor.motion__bedroom_99
  from: 'on'
condition:
- condition: state
  entity_id: light.bedroom_light_10
  state: 'on'  
action:
- service: script.timer_bedroom_set