trigger:
- platform: time
  after: '01:19:00'
condition:
- condition: template
  value_template: >-
    {% for entity_id in states.group.battery_levels.attributes.entity_id if states(entity_id) | int < 60 %}
    {%- if loop.first -%}
    {{ true }}
    {%- endif -%}
    {% endfor %}
action:
- service: notify.phoebe
  data:
    message: >-
      {% set output = ' ' %}
      {% for entity_id in states.group.battery_levels.attributes.entity_id %}
      {% set Data = entity_id.split('.') %}
      {% set friendly_name = states[Data[0]][Data[1]].attributes.friendly_name %}
      {%- if states(entity_id)|int < 60 -%}
      {%- set output = output +friendly_name+' level is '+states(entity_id) +'%! ' -%}
      {%- endif -%}
      {% if loop.last %}
      {{ output }}
      {% elif states(entity_id)|int < 60 %}
      {% set output = output + '\n' %}
      {% endif %}
      {% endfor %}    