#### When someone arrives, turn on the lights
#### Only if no one is sleeping and it is after sunset

alias:  Arrival Lights
trigger:
- platform: state
  entity_id: group.household_occupancy
  to: 'home'
condition:
- condition: state
  entity_id: sensor.darkness
  state: 'true'
- condition: state
  entity_id: input_boolean.sleep_mode
  state: 'off'
action:
- service: scene.turn_on
  entity_id: scene.livingroom_normal
- service: light.turn_on
  entity_id: light.stairway_light_25
  data:
    brightness: 155