#### When it's dark, turn on the house lights
#### Only if no one is sleeping and after 10:20AM

alias:  Darkness Lights On
trigger:
- platform: state
  entity_id: sensor.darkness
  from: 'false'

condition:
- condition: state
  entity_id: group.household_occupancy
  state: 'home'
- condition: state
  entity_id: input_boolean.sleep_mode
  state: 'off'
- condition: time
  after: '10:20:00'
  before: '21:00:00'
action:
- service: scene.turn_on
  entity_id: scene.house_lights_high