

### Automations #####################################
automation:

### Environment Based ###

# Turn on the Porch Light around Sunset
- alias: Porch Light On
  trigger:
  - platform: sun
    event: sunset
    offset: '00:30:00'
  action:
  - service: light.turn_on
    entity_id: light.front_porch_light_24
    
# Turn off the Porch Light at Sunrise
- alias: Porch Light Off
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.front_porch_light_24
    
# When it's dark, turn on the house lights
# Only if no one is sleeping and after 10:20AM
- alias:  Darkness Lights On
  trigger:
  - platform: state
    entity_id: sensor.darkness
    from: 'false'
  condition:
  - condition: state
    entity_id: group.household_occupancy
    state: 'home'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: time
    after: '10:20:00'
    before: '21:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.house_lights_high    
    
### Occupancy Based ###

# Turn lights off at when house is empty

- alias: Unoccupied Lights
  trigger:
  - platform: state
    entity_id: group.household_occupancy
    from: 'home'
  action:
  - service: light.turn_off
    entity_id: group.interior_lights
    
# When someone arrives, turn on the lights
# Only if no one is sleeping and it is dark
- alias:  Arrival Lights
  trigger:
  - platform: state
    entity_id: group.household_occupancy
    to: 'home'
  condition:
  - condition: state
    entity_id: sensor.darkness
    state: 'true'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.livingroom_normal
  - service: light.turn_on
    entity_id: light.stairway_light_25
    data:
      brightness: 155    
    
### Logic Based ###

# When closet light is turned on, set a script
# to turn off after a short time
- alias: Closet Light Timer Set
  trigger:
    platform: state
    entity_id: light.closet_light_3
    from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: script.timer_closet_short_set
        state: 'off'
      - condition: state
        entity_id: script.timer_closet_long_set
        state: 'off'  
  action:
  - service: script.turn_on
    entity_id: script.timer_closet_short_set    

# When closet light is turned on soon after the short script
# is run, set a script to extend time
- alias: Closet Light Extend Timer
  trigger:
    platform: state
    entity_id: light.closet_light_3
    from: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: script.timer_closet_short_set
        state: 'on'
      - condition: state
        entity_id: script.timer_closet_long_set
        state: 'on'  
  action:
  - service: script.turn_off
    entity_id: script.timer_closet_short_set
  - service: script.turn_off
    entity_id: script.timer_closet_long_set
  - service: script.turn_on
    entity_id: script.timer_closet_long_set     
    
    
    
    