### Setup for betime automations
### Uses Tasker Profiles

### Input Boolean for UI Switch ############################

input_boolean:
  sleep_mode:
    name: Sleep Mode
    initial: off
    icon: mdi:sleep

### Scenes #####################################

scene:
### Upstairs Off ###
- name: Upstairs Off
  entities:
    light.closet_light_3:
      state: off
    light.desk_lights_14:
      state: off
    light.stairway_light_25:
      state: off

### Downstairs Off ###
- name: Downstairs Off
  entities:
    light.dining_light_26:
      state: off      
    light.fireplace_light_85:
      state: off

### Goodnight Scene ###
- name: Goodnight
  entities:
    light.closet_light_3:
      state: off
    light.desk_lights_14:
      state: off
    light.stairway_light_25:
      state: off
    light.dining_light_26:
      state: off      
    light.fireplace_light_85:
      state: off
    remote.living_room:
      state: off
      
### Automations ################################

automation:

###  Turns Sleep Mode Off when the kitchen motion is triggered after 6 AM
- alias: Sleep Mode Off
  trigger:
  - platform: state
    entity_id: binary_sensor.motion__kitchen_27
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  - condition: and
    conditions:
    - condition: time
      after: '06:01:00'
    - condition: time
      before: '20:59:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.sleep_mode
  - service: joaoapps_join.phoebe_join_send_tasker
    data:
      command: "setvar=:=SLEEPING=:=no"
      
###  Turns Sleep Mode On when all of the lights are turned off and 
###  the house is occupied
- alias: Sleep Mode On
  trigger:
  - platform: state
    entity_id: group.interior_lights
    to: 'off'
    for: '00:02:00'
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: group.household_occupancy
    state: 'home'
  - condition: or
    conditions:
    - condition: time
      after: '21:00:00'
    - condition: time
      before: '06:00:00'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.sleep_mode 
  - service: cover.close_cover
    entity_id: cover.patio_door_shade_92
  - service: joaoapps_join.phoebe_join_send_tasker
    data:
      command: "setvar=:=SLEEPING=:=yes"